
language: swift
osx_image: xcode73
branches:
  only:
    - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
- gem install xcpretty -N
script:
- set -o pipefail
- xcodebuild -project "Example/ExampleSwift.xcodeproj" -scheme "ExampleSwift" -sdk iphonesimulator
  -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=YES build | xcpretty -c
- pod lib lint --quick