
language: swift
osx_image: xcode7.3
branches:
  only:
    - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
- set -o pipefail
- xcodebuild -project "Example/ExampleSwift.xcodeproj" -scheme "ExampleSwift" -sdk iphonesimulator9.3 -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=YES build
- pod lib lint --quick